"""Coverage dashboard generator for alloy-devices-yml.

`add-coverage-index-and-dashboard` (Phase 2.3) renders
``coverage-dashboard.md`` from ``index.yml`` showing:

* Vendor × source matrix with per-cell chip counts.
* Top-level summary (total devices, vendor count, family count).
* Schema-version distribution.

Source-pin freshness is tracked separately by the extractor's
pin-bump tooling and not part of the index — it lives in
``data/source_pins.toml`` and a future change can layer that
into the dashboard.
"""

from __future__ import annotations

from collections import Counter
from pathlib import Path

from alloy_data_extractor.index import CatalogIndex, build_index


def _vendor_source_matrix(index: CatalogIndex) -> tuple[
    tuple[str, ...],
    tuple[str, ...],
    dict[tuple[str, str], int],
]:
    vendors = sorted({e.vendor for e in index.entries})
    sources = sorted({e.source_id for e in index.entries})
    counts: Counter[tuple[str, str]] = Counter()
    for entry in index.entries:
        counts[(entry.vendor, entry.source_id)] += 1
    return tuple(vendors), tuple(sources), dict(counts)


def render_dashboard(index: CatalogIndex) -> str:
    """Render the coverage dashboard as Markdown."""
    vendors, sources, counts = _vendor_source_matrix(index)
    schema_distribution: Counter[str] = Counter(e.schema_version for e in index.entries)

    lines: list[str] = []
    lines.append("# alloy-devices-yml coverage dashboard")
    lines.append("")
    lines.append("> Auto-generated by `alloy-data-extract dashboard`. Do not edit.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Total devices**: {index.total_devices}")
    lines.append(f"- **Vendors**: {index.vendor_count}")
    lines.append(f"- **Families**: {index.family_count}")
    versions = ", ".join(index.schema_versions) or "<none>"
    lines.append(f"- **Schema versions in catalog**: {versions}")
    lines.append("")
    lines.append("## Coverage by vendor and source")
    lines.append("")
    if not vendors:
        lines.append("> Catalog is empty.")
        lines.append("")
    else:
        header = "| Vendor | " + " | ".join(sources) + " | Total |"
        separator = "|---|" + "---|" * len(sources) + "---|"
        lines.append(header)
        lines.append(separator)
        for vendor in vendors:
            row_total = 0
            cells: list[str] = []
            for source in sources:
                count = counts.get((vendor, source), 0)
                row_total += count
                cells.append(str(count) if count else "—")
            lines.append(f"| {vendor} | " + " | ".join(cells) + f" | **{row_total}** |")
        # Footer row: per-source totals
        column_totals: list[int] = []
        for source in sources:
            column_totals.append(sum(counts.get((v, source), 0) for v in vendors))
        grand_total = sum(column_totals)
        lines.append(
            "| **Total** | "
            + " | ".join(f"**{c}**" for c in column_totals)
            + f" | **{grand_total}** |"
        )
        lines.append("")
    lines.append("## Schema version distribution")
    lines.append("")
    if schema_distribution:
        lines.append("| schema_version | devices |")
        lines.append("|---|---|")
        for version, count in sorted(schema_distribution.items()):
            lines.append(f"| {version} | {count} |")
    else:
        lines.append("> Catalog is empty.")
    lines.append("")
    return "\n".join(lines)


def write_dashboard(*, data_repo_root: Path, index: CatalogIndex | None = None) -> Path:
    """Write ``coverage-dashboard.md`` at ``data_repo_root``."""
    if index is None:
        index = build_index(data_repo_root)
    out_path = data_repo_root / "coverage-dashboard.md"
    out_path.write_text(render_dashboard(index), encoding="utf-8")
    return out_path


__all__ = ["render_dashboard", "write_dashboard"]
